INSERT INTO `words` (`language`, `chinese`, `pinyin`, `pos`, `meaning`, `hskLevel`, `chineseExample`, `examplePinyin`) VALUES
('chinese', '爱', 'ài', 'verb', 'to love', '1', '我爱你。', 'Wǒ ài nǐ.'),
('chinese', '八', 'bā', 'number', 'eight', '1', '我有八个苹果。', 'Wǒ yǒu bā ge píngguǒ.'),
('chinese', '爸爸', 'bàba', 'noun', 'dad', '1', '我的爸爸很高。', 'Wǒ de bàba hěn gāo.'),
('chinese', '白天', 'báitiān', 'noun', 'daytime', '1', '白天很热。', 'Báitiān hěn rè.'),
('chinese', '百', 'bǎi', 'number', 'hundred', '1', '这件衣服一百块钱。', 'Zhè jiàn yīfu yībǎi kuài qián.'),
('chinese', '半', 'bàn', 'number', 'half', '1', '现在是两点半。', 'Xiànzài shì liǎng diǎn bàn.'),
('chinese', '包子', 'bāozi', 'noun', 'steamed bun', '1', '我喜欢吃包子。', 'Wǒ xǐhuān chī bāozi.'),
('chinese', '杯子', 'bēizi', 'noun', 'cup', '1', '请给我一个杯子。', 'Qǐng gěi wǒ yī ge bēizi.'),
('chinese', '本', 'běn', 'classifier', 'measure word for books', '1', '我有三本书。', 'Wǒ yǒu sān běn shū.'),
('chinese', '边', 'biān', 'noun', 'side', '1', '房子在街的左边。', 'Fángzi zài jiē de zuǒ biān.'),
('chinese', '病', 'bìng', 'noun', 'illness', '1', '他生病了。', 'Tā shēngbìng le.'),
('chinese', '不', 'bù', 'adverb', 'not', '1', '我不喜欢这个。', 'Wǒ búxǐhuān zhège.'),
('chinese', '菜', 'cài', 'noun', 'vegetable', '1', '这个菜很好吃。', 'Zhège cài hěn hǎochī.'),
('chinese', '茶', 'chá', 'noun', 'tea', '1', '我想喝茶。', 'Wǒ xiǎng hē chá.'),
('chinese', '唱', 'chàng', 'verb', 'to sing', '1', '她喜欢唱歌。', 'Tā xǐhuān chànggē.'),
('chinese', '车', 'chē', 'noun', 'car', '1', '我的车是红色的。', 'Wǒ de chē shì hóngsè de.'),
('chinese', '吃', 'chī', 'verb', 'to eat', '1', '我们一起吃饭。', 'Wǒmen yīqǐ chīfàn.'),
('chinese', '穿', 'chuān', 'verb', 'to wear', '1', '今天穿什么衣服？', 'Jīntiān chuān shénme yīfu?'),
('chinese', '大', 'dà', 'adjective', 'big', '1', '这个房间很大。', 'Zhège fángjiān hěn dà.'),
('chinese', '大家', 'dàjiā', 'pronoun', 'everyone', '1', '大家好！', 'Dàjiā hǎo!');
